apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-app
  namespace: lab-04
  labels:
    app: load-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-test-app
  template:
    metadata:
      labels:
        app: load-test-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: [ALL]
---
apiVersion: v1
kind: Service
metadata:
  name: load-test-app
  namespace: lab-04
spec:
  selector:
    app: load-test-app
  ports:
    - port: 80
      targetPort: 8080
